### ISSUE TITLE
Generate Batteries

### ISSUE THREAD

**Issue by texastoland** [tfausak/purescript-batteries#31]
Placeholder for brainstorming. I envision a JSON, YAML, or TOML file (see [`get-config`](JSON, YAML, or TOML)) that drives creating _any_ custom prelude including `{Batteries}.purs`, `bower.json`, and the readme. Our configuration should describe the following:
## MVP
- Included packages: first-party (e.g. `purescript-prelude`) to third-party but de facto (e.g. `purescript-aff`)
- Allowable versions: generally caret ranges allowing any patch version (e.g. `^1.2.x`)
- Included modules per package (e.g. `Prelude` but not composed modules like `Data.Void`).
- Included identifiers per module: also specify what which identifiers shadow others
- Global identifier blacklist (e.g. `singleton` is everywhere)
## Stretch Goals
- Monitored organizations (e.g. @purescript, @purescript-contrib, @purescripters, possibly prominent contributors like @slamdata): warn when new packages not included
- Newer versions: warn when available version exceeds range (keeps automated builds current)
- Unreferenced modules: warn when any module is neither exported nor blacklisted (still error for missing modules e.g. `X.Unsafe`)
- Unreferenced identifiers: warn when any identifier is neither exported nor blacklisted

**Comment by tfausak** [comment]
Here are the things Batteries needs to know:

- Which packages to include, from the first-party ones like purescript-prelude to the third-party but de facto standard ones like purescript-aff.

  - It would be nice if packages from certain GitHub organizations would always be considered. I would like it if I got a warning about some new package under github.com/purescript that Batteries doesn't include.

- The allowable versions of those packages. These should almost always be [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) like `^1.2.3`. It's probably fine to allow any patch version, so most should be `^1.2.x`. 

  - It would be nice if newer versions outside the allowable versions generated a warning. Then I could set up nightly builds to make sure Batteries is up to date with everything.

- For each package, which modules should be exported? For instance, maybe we only want `Prelude` from purescript-prelude instead of all the smaller modules like `Data.Void`. 

  - It would be nice if warnings were generated for modules that are neither exported nor explicitly ignored. Modules that no longer exist (like `X.Unsafe` nowadays) would of course be errors. 

- For each module, which identifiers should be exported? 

  - Like modules, all identifiers should be required to be explicitly exported or ignored. 

  - I'm not interested in providing aliases. If there are collisions in the "base" libraries, they should be resolved by those libraries. Or something else can build on top of Batteries. 

  - It would be nice if each "type" of identifier ended up in a separate module. For example, `$` might end up in `Batteries.Operators`. The top-level `Batteries` could re-export everything, allowing you to have a really clean namespace with `import Batteries as B; import Batteries.Operators (..)`. (This is more-or-less what I do with Neon.) 

  - Some identifiers should be globally banned to avoid problems. For example, `singleton` is everywhere. It would be bad to accidentally export that from something. 

A lot of "nice to have"s in there 😄

**Comment by tfausak** [comment]
Ignoring all the stretch goals, you could get everything you need from a data structure like this:

``` js
{ "purescript-prelude@^1.0.x":
  [ "Prelude.unit"
  , ...
  ]
, ...
}
```

**Comment by texastoland** [comment]
> I'm not interested in providing aliases.

Alternatively could we push them to monomorphic packages like `Batteries.Mono.String`?

**Comment by tfausak** [comment]
Not sure what you mean by that. What do you mean "monomorphic"? And did you mean "modules" instead of "packages"?

Do you have an example of something that might be aliased?

**Comment by texastoland** [comment]
Yep. By monomorphic I meant functions like `floor` that aren't implemented in a general way or are specialized (like `Data.String.drop`).

**Comment by tfausak** [comment]
Oh, I see. I stand by my original statement:

> If there are collisions in the "base" libraries, they should be resolved by those libraries.

Same goes for optimizations and specializations. Either you make go with the slow, general, unambiguous function or you import the module that gives you the fast, specialized, ambiguous one. 

See #1, #9, and #16 for some previous discussion about this.

**Comment by texastoland** [comment]
RE: #9 that's easy for `Data.List` and a royal PITA for `Control.Monad.Eff.Console` and friends. I agree with your conclusions in previous ticket regarding work but in this case it's largely automated in the same way something like `Batteries.Operators` is. And in the same vane as Neon we'd just be patching a crappy naming scheme until addressed on a higher level.

**Comment by texastoland** [comment]
Thinking further I think segregating operators is a bad idea. Neon does it to encourage named functions. But the purpose of `Batteries` is to reduce imports.

**Comment by tfausak** [comment]
I changed my mind about having an operators module. I think Batteries should continue to wrap up a bunch of packages. If some other library wants to provide a nice interface, it can build on top of Batteries.

**Comment by tfausak** [comment]
This would be nice to have, but I'm not really maintaining this library anymore.
